configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;csp_apps_pic32cm_mc00;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;csp_apps_sam_rh71;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.3.64\atdf\ATSAME54P20A.atdf
