configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;bootloader;bootloader_apps_uart;bsp;core;crypto;cryptoauthlib;csp;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;expresslogic_threadx;gfx;gfx_apps;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.3.64\atdf\ATSAME54P20A.atdf
