format_version: v1.0
type: UniqueComponent
attributes: {id: tcc0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: INTR_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_OTHER_IRQn}
  - type: String
    attributes: {id: PWM_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_PWMCallbackRegister}
  - type: String
    attributes: {id: PWM_GET_PERIOD_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_PWM24bitPeriodGet}
  - type: String
    attributes: {id: PWM_OUTPUT_DISABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_PWMPatternSet}
  - type: String
    attributes: {id: PWM_OUTPUT_ENABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_PWMPatternSet}
  - type: Hex
    attributes: {id: PWM_PATTERN_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: '119'}
  - type: Hex
    attributes: {id: PWM_PH_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: '7'}
  - type: String
    attributes: {id: PWM_PH_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0CHANNEL0}
  - type: String
    attributes: {id: PWM_PH_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0CHANNEL1}
  - type: String
    attributes: {id: PWM_PH_W}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0CHANNEL2}
  - type: String
    attributes: {id: PWM_SET_DUTY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_PWM24bitDutySet}
  - type: String
    attributes: {id: PWM_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_PWMStart}
  - type: String
    attributes: {id: PWM_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc0, value: TCC0_PWMStop}
  - type: KeyValueSet
    attributes: {id: TCC_0_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_0_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TCC_1_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_1_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TCC_2_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_2_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TCC_3_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_3_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TCC_4_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_4_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TCC_5_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_5_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TCC_CTRLBSET_DIR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: TCC_DTHS_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** High side dead time is 1.06666666667 uS ****'}
  - type: Comment
    attributes: {id: TCC_DTLS_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Low side dead time is 1.06666666667 uS ****'}
  - type: Comment
    attributes: {id: TCC_FREQUENCY}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 10001 Hz ****'}
  - type: Boolean
    attributes: {id: TCC_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: TCC_PER_PER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5999'}
  - type: KeyValueSet
    attributes: {id: TCC_WAVE_WAVEGEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: TCC_WEXCTRL_DTHS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '128'}
  - type: Integer
    attributes: {id: TCC_WEXCTRL_DTLS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '128'}
- type: ElementPosition
  attributes: {x: '38', y: '110', id: tcc0}
